INSERT INTO SERVICE (DESCRIPTION) VALUES ('TEST_SERVICE_1');
INSERT INTO SERVICE (DESCRIPTION) VALUES ('TEST_SERVICE_2');
INSERT INTO SERVICE (DESCRIPTION) VALUES ('TEST_SERVICE_3');
INSERT INTO SERVICE (DESCRIPTION) VALUES ('TEST_SERVICE_4');

INSERT INTO REGION (DESCRIPTION) VALUES ('TEST_REGION_1');
INSERT INTO REGION (DESCRIPTION) VALUES ('TEST_REGION_1');
INSERT INTO REGION (DESCRIPTION) VALUES ('TEST_REGION_1');
INSERT INTO REGION (DESCRIPTION) VALUES ('TEST_REGION_1');

